apiVersion: v1
kind: Service
metadata:
  name: {{ include "autosd-template.fullname" . }}
  labels:
    {{- include "autosd-template.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: socat
      protocol: TCP
      name: socat
  selector:
    {{- include "autosd-template.selectorLabels" . | nindent 4 }}
