apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: automotive
  description: Red Hat Automotive Developer Platform Samples
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: auto@demo.redhat.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: jumpstarter
  description: Jumpstarter Development Samples
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: jumpstarter@demo.redhat.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: rhdh
  description: Red Hat Developer Hub
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: rhdh@opentlc.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  children: []
---
# https://www.dicebear.com/playground/?style=dylan
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
spec:
  profile:
    # Intentional no displayName for testing
    email: user1@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user2
spec:
  profile:
    # Intentional no displayName for testing
    email: user2@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Adrian
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user3
spec:
  profile:
    # Intentional no displayName for testing
    email: user3@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Jude
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user4
spec:
  profile:
    # Intentional no displayName for testing
    email: user4@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Andrea
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user5
spec:
  profile:
    # Intentional no displayName for testing
    email: user5@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Brian
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user6
spec:
  profile:
    # Intentional no displayName for testing
    email: user6@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Kimberly
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user7
spec:
  profile:
    # Intentional no displayName for testing
    email: user7@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Jade
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user8
spec:
  profile:
    # Intentional no displayName for testing
    email: user8@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user9
spec:
  profile:
    # Intentional no displayName for testing
    email: user9@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user10
spec:
  profile:
    # Intentional no displayName for testing
    email: user10@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user11
spec:
  profile:
    # Intentional no displayName for testing
    email: user11@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user12
spec:
  profile:
    # Intentional no displayName for testing
    email: user12@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user13
spec:
  profile:
    # Intentional no displayName for testing
    email: user13@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user14
spec:
  profile:
    # Intentional no displayName for testing
    email: user14@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user15
spec:
  profile:
    # Intentional no displayName for testing
    email: user15@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user16
spec:
  profile:
    # Intentional no displayName for testing
    email: user16@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user17
spec:
  profile:
    # Intentional no displayName for testing
    email: user17@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user18
spec:
  profile:
    # Intentional no displayName for testing
    email: user18@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user19
spec:
  profile:
    # Intentional no displayName for testing
    email: user19@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user20
spec:
  profile:
    # Intentional no displayName for testing
    email: user20@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user21
spec:
  profile:
    # Intentional no displayName for testing
    email: user21@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user22
spec:
  profile:
    # Intentional no displayName for testing
    email: user22@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user23
spec:
  profile:
    # Intentional no displayName for testing
    email: user23@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user24
spec:
  profile:
    # Intentional no displayName for testing
    email: user24@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user25
spec:
  profile:
    # Intentional no displayName for testing
    email: user25@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user26
spec:
  profile:
    # Intentional no displayName for testing
    email: user26@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user27
spec:
  profile:
    # Intentional no displayName for testing
    email: user27@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user28
spec:
  profile:
    # Intentional no displayName for testing
    email: user28@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user29
spec:
  profile:
    # Intentional no displayName for testing
    email: user29@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user30
spec:
  profile:
    # Intentional no displayName for testing
    email: user30@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user31
spec:
  profile:
    # Intentional no displayName for testing
    email: user31@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user32
spec:
  profile:
    # Intentional no displayName for testing
    email: user32@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user33
spec:
  profile:
    # Intentional no displayName for testing
    email: user33@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user34
spec:
  profile:
    # Intentional no displayName for testing
    email: user34@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user35
spec:
  profile:
    # Intentional no displayName for testing
    email: user35@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user36
spec:
  profile:
    # Intentional no displayName for testing
    email: user36@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user37
spec:
  profile:
    # Intentional no displayName for testing
    email: user37@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user38
spec:
  profile:
    # Intentional no displayName for testing
    email: user38@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user39
spec:
  profile:
    # Intentional no displayName for testing
    email: user39@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user40
spec:
  profile:
    # Intentional no displayName for testing
    email: user40@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user41
spec:
  profile:
    # Intentional no displayName for testing
    email: user41@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user42
spec:
  profile:
    # Intentional no displayName for testing
    email: user42@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user43
spec:
  profile:
    # Intentional no displayName for testing
    email: user43@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user44
spec:
  profile:
    # Intentional no displayName for testing
    email: user44@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user45
spec:
  profile:
    # Intentional no displayName for testing
    email: user45@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user46
spec:
  profile:
    # Intentional no displayName for testing
    email: user46@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user47
spec:
  profile:
    # Intentional no displayName for testing
    email: user47@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user48
spec:
  profile:
    # Intentional no displayName for testing
    email: user48@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user49
spec:
  profile:
    # Intentional no displayName for testing
    email: user49@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user50
spec:
  profile:
    # Intentional no displayName for testing
    email: user10@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user51
spec:
  profile:
    # Intentional no displayName for testing
    email: user51@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user52
spec:
  profile:
    # Intentional no displayName for testing
    email: user52@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user53
spec:
  profile:
    # Intentional no displayName for testing
    email: user53@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user54
spec:
  profile:
    # Intentional no displayName for testing
    email: user54@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user55
spec:
  profile:
    # Intentional no displayName for testing
    email: user55@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user56
spec:
  profile:
    # Intentional no displayName for testing
    email: user56@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user57
spec:
  profile:
    # Intentional no displayName for testing
    email: user57@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user58
spec:
  profile:
    # Intentional no displayName for testing
    email: user58@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user59
spec:
  profile:
    # Intentional no displayName for testing
    email: user9@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user60
spec:
  profile:
    # Intentional no displayName for testing
    email: user60@opentlc.com
    picture: https://api.dicebear.com/9.x/dylan/svg?seed=Aiden
  memberOf: [automotive]
